import streamlit as st
import json
import os
from fpdf import FPDF
from datetime import datetime

# --- KONFIGURASI FILE PENYIMPANAN ---
CONFIG_FILE = 'laundry_config.json'

def load_config():
    """Membaca konfigurasi dari file JSON jika ada"""
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r') as f:
                return json.load(f)
        except:
            return {}
    return {}

def save_config(data):
    """Menyimpan konfigurasi ke file JSON"""
    try:
        with open(CONFIG_FILE, 'w') as f:
            json.dump(data, f)
        return True
    except Exception as e:
        st.error(f"Gagal menyimpan: {e}")
        return False

# --- FUNGSI GENERATE PDF ---
def create_pdf(data_input, hasil_hpp, hasil_profit):
    """Membuat file PDF dari hasil perhitungan"""
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 15)
            self.cell(0, 10, 'Laporan Analisa Laundry Biz OS', 0, 1, 'C')
            self.set_font('Arial', 'I', 10)
            self.cell(0, 10, f'Dicetak pada: {datetime.now().strftime("%d-%m-%Y %H:%M")}', 0, 1, 'C')
            self.line(10, 30, 200, 30)
            self.ln(10)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, 'Page ' + str(self.page_no()) + ' | Generated by Laundry Biz OS', 0, 0, 'C')

    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # BAGIAN 1: HASIL ANALISA (HPP)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "1. Analisa HPP (Harga Pokok Produksi)", 0, 1)
    pdf.set_font("Arial", size=11)
    
    # Membuat tabel sederhana dengan cell
    col_width = 90
    row_height = 8
    
    pdf.cell(col_width, row_height, f"HPP per Load (1x Cuci):", border=1)
    pdf.cell(col_width, row_height, f"Rp {int(hasil_hpp['hpp_load']):,}", border=1, ln=1)
    
    pdf.cell(col_width, row_height, f"HPP per Kg (Real):", border=1)
    pdf.cell(col_width, row_height, f"Rp {int(hasil_hpp['hpp_kg']):,}", border=1, ln=1)
    
    pdf.cell(col_width, row_height, f"Kapasitas Efektif:", border=1)
    pdf.cell(col_width, row_height, f"{hasil_hpp['kapasitas']:.1f} Kg", border=1, ln=1)
    
    pdf.ln(5)

    # BAGIAN 2: RINCIAN BIAYA
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "2. Rincian Biaya per Cycle", 0, 1)
    pdf.set_font("Arial", size=11)
    
    pdf.cell(col_width, row_height, f"Biaya Listrik:", border=1)
    pdf.cell(col_width, row_height, f"Rp {int(hasil_hpp['biaya_listrik']):,}", border=1, ln=1)
    
    pdf.cell(col_width, row_height, f"Biaya Gas Dryer:", border=1)
    pdf.cell(col_width, row_height, f"Rp {int(hasil_hpp['biaya_gas']):,}", border=1, ln=1)
    
    pdf.cell(col_width, row_height, f"Biaya Chemical (Sabun/Parfum):", border=1)
    pdf.cell(col_width, row_height, f"Rp {int(hasil_hpp['biaya_chem']):,}", border=1, ln=1)
    
    pdf.ln(5)

    # BAGIAN 3: SIMULASI PROFIT
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "3. Simulasi Keuntungan", 0, 1)
    pdf.set_font("Arial", size=11)

    pdf.cell(col_width, row_height, f"Target Omzet:", border=1)
    pdf.cell(col_width, row_height, f"Rp {int(hasil_profit['target_omzet']):,}", border=1, ln=1)
    
    pdf.cell(col_width, row_height, f"Estimasi Laba Bersih:", border=1)
    pdf.cell(col_width, row_height, f"Rp {int(hasil_profit['laba_bersih']):,}", border=1, ln=1)
    
    pdf.cell(col_width, row_height, f"Target Produksi Harian:", border=1)
    pdf.cell(col_width, row_height, f"{int(hasil_profit['target_kg'])} Kg/hari", border=1, ln=1)

    pdf.ln(5)

    # BAGIAN 4: PARAMETER INPUT (DATA TEKNIS)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "4. Parameter Teknis (Input Data)", 0, 1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, 
        f"Tarif Listrik: Rp {data_input['tarif_listrik']}/kWh\n"
        f"Harga Gas: Rp {data_input['harga_gas']}\n"
        f"Mesin: {data_input['watt_cuci']}W Cuci, {data_input['durasi_cuci']}m Cuci, {data_input['durasi_kering']}m Kering\n"
        f"Chemical: Deterjen Rp {data_input['harga_deterjen']} (Tk {data_input['takaran_det']}ml)"
    )

    # Output PDF ke string binary
    return pdf.output(dest='S').encode('latin-1')

# --- KONFIGURASI HALAMAN ---
st.set_page_config(
    page_title="Laundry Biz OS",
    page_icon="👕",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- FUNGSI LOGIN ---
def check_password():
    if "password_correct" not in st.session_state:
        st.session_state["password_correct"] = False

    if not st.session_state["password_correct"]:
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.markdown("<br><br>", unsafe_allow_html=True)
            st.title("🔐 Laundry Biz OS")
            st.markdown("Silakan masukkan **Kode Lisensi** untuk mengakses aplikasi.")
            with st.form("login_form"):
                password = st.text_input("Kode Lisensi", type="password", placeholder="Masukkan kode...")
                submit_btn = st.form_submit_button("Buka Aplikasi", use_container_width=True)
                if submit_btn:
                    if password == "LAUNDRY2025":
                        st.session_state["password_correct"] = True
                        st.rerun()
                    else:
                        st.error("⛔ Kode lisensi salah.")
            st.caption("© 2025 Laundry Biz OS. Licensed User Only.")
        return False
    return True

# --- APLIKASI UTAMA ---
if check_password():
    
    # 1. LOAD DATA TERSIMPAN
    defaults = load_config()
    
    # --- HEADER ---
    st.title("👕 Laundry Biz OS: Dashboard Operasional")
    st.markdown("Kalkulator pintar untuk menghitung HPP dan Profitabilitas.")
    st.divider()

    # --- INPUT DATA ---
    with st.sidebar:
        st.header("⚙️ Panel Kontrol")
        
        with st.expander("1. Biaya Energi & Utilitas", expanded=True):
            tarif_listrik = st.number_input("Listrik per kWh (Rp)", value=defaults.get('tarif_listrik', 1444), step=100)
            harga_gas = st.number_input("Harga Gas 12kg (Rp)", value=defaults.get('harga_gas', 215000), step=1000)

        with st.expander("2. Bahan Baku (Chemical)"):
            harga_deterjen = st.number_input("Hrg Deterjen 5L", value=defaults.get('harga_deterjen', 85000))
            takaran_det = st.number_input("Takaran Det (ml)", value=defaults.get('takaran_det', 50))
            harga_parfum = st.number_input("Hrg Parfum 5L", value=defaults.get('harga_parfum', 175000))
            takaran_par = st.number_input("Takaran Par (ml)", value=defaults.get('takaran_par', 20))
            harga_plastik = st.number_input("Plastik per Baju (Rp)", value=defaults.get('harga_plastik', 500))

        with st.expander("3. Spesifikasi Mesin"):
            kapasitas_mesin = st.number_input("Kapasitas Mesin (Kg)", value=defaults.get('kapasitas_mesin', 7.0))
            watt_cuci = st.number_input("Watt Mesin Cuci", value=defaults.get('watt_cuci', 450))
            durasi_cuci = st.number_input("Durasi Cuci (Menit)", value=defaults.get('durasi_cuci', 45))
            durasi_kering = st.number_input("Durasi Dryer (Menit)", value=defaults.get('durasi_kering', 60))
            gas_per_cycle = st.slider("Gas per Cycle (kg)", 0.1, 1.0, defaults.get('gas_per_cycle', 0.4))

        with st.expander("4. Biaya Tetap (Bulanan)"):
            biaya_tetap = st.number_input("Total Gaji + Sewa (Rp)", value=defaults.get('biaya_tetap', 5000000), step=100000)

        st.markdown("---")
        
        # TOMBOL SIMPAN KONFIGURASI
        if st.button("💾 Simpan Konfigurasi", use_container_width=True):
            current_config = {
                'tarif_listrik': tarif_listrik, 'harga_gas': harga_gas,
                'harga_deterjen': harga_deterjen, 'takaran_det': takaran_det,
                'harga_parfum': harga_parfum, 'takaran_par': takaran_par,
                'harga_plastik': harga_plastik, 'kapasitas_mesin': kapasitas_mesin,
                'watt_cuci': watt_cuci, 'durasi_cuci': durasi_cuci,
                'durasi_kering': durasi_kering, 'gas_per_cycle': gas_per_cycle,
                'biaya_tetap': biaya_tetap
            }
            if save_config(current_config):
                st.toast("Pengaturan berhasil disimpan!", icon="✅")
            
    # --- LOGIKA PERHITUNGAN ---
    kwh_cuci = (watt_cuci / 1000) * (durasi_cuci / 60)
    kwh_dryer = (150 / 1000) * (durasi_kering / 60) 
    biaya_listrik = (kwh_cuci + kwh_dryer) * tarif_listrik
    biaya_gas_cycle = (harga_gas / 12) * gas_per_cycle
    biaya_deterjen_cycle = (harga_deterjen / 5000) * takaran_det
    biaya_parfum_cycle = (harga_parfum / 5000) * takaran_par
    
    hpp_per_load = biaya_listrik + biaya_gas_cycle + biaya_deterjen_cycle + biaya_parfum_cycle + harga_plastik
    kapasitas_efektif = kapasitas_mesin * 0.8
    hpp_per_kg = hpp_per_load / kapasitas_efektif

    # --- MAIN DASHBOARD ---
    tab1, tab2 = st.tabs(["📊 Analisa HPP", "💰 Simulasi Profit"])

    # VARIABEL UNTUK EXPORT (Diinisialisasi di sini)
    harga_jual = 0
    target_omzet = 0
    laba_bersih = 0
    kg_per_hari_needed = 0

    with tab1:
        st.subheader("Berapa modal yang keluar setiap kali mencuci?")
        col_m1, col_m2, col_m3 = st.columns(3)
        col_m1.metric("HPP per Kg", f"Rp {int(hpp_per_kg):,}", help="Modal murni per Kg pakaian")
        col_m2.metric("HPP per Load", f"Rp {int(hpp_per_load):,}", help="Total biaya sekali mesin jalan")
        col_m3.metric("Kapasitas Efektif", f"{kapasitas_efektif:.1f} Kg", help="Asumsi mesin terisi 80%")

        st.markdown("#### Rincian Biaya per Load")
        st.write(f"⚡ **Listrik:** Rp {int(biaya_listrik):,}")
        st.progress(biaya_listrik/hpp_per_load)
        st.write(f"🔥 **Gas Dryer:** Rp {int(biaya_gas_cycle):,}")
        st.progress(biaya_gas_cycle/hpp_per_load)
        st.write(f"🧼 **Sabun & Parfum:** Rp {int(biaya_deterjen_cycle + biaya_parfum_cycle):,}")
        st.progress((biaya_deterjen_cycle + biaya_parfum_cycle)/hpp_per_load)

    with tab2:
        st.subheader("Kalkulator Target Keuntungan")
        col_sim1, col_sim2 = st.columns([1, 2])
        
        with col_sim1:
            st.markdown("### 🎯 Atur Target")
            harga_jual = st.number_input("Harga Jual / Kg", value=defaults.get('harga_jual', 6000), step=500)
            target_omzet = st.number_input("Target Omzet / Bulan", value=defaults.get('target_omzet', 15000000), step=500000)

        with col_sim2:
            laba_kotor = target_omzet - ((target_omzet/harga_jual) * hpp_per_kg)
            laba_bersih = laba_kotor - biaya_tetap
            kg_per_hari_needed = (target_omzet / harga_jual) / 30
            
            st.markdown("### 📈 Hasil Simulasi")
            c_res1, c_res2 = st.columns(2)
            c_res1.metric("Estimasi Laba Bersih", f"Rp {int(laba_bersih):,}", delta="Net Profit")
            c_res2.metric("Target Load Cucian", f"{int(kg_per_hari_needed)} Kg / Hari", delta="Productivity")
            
            if laba_bersih < 0:
                st.error("⚠️ Rugi. Tingkatkan target atau harga jual.")
            else:
                st.success("✅ Bisnis Profitable! Target tercapai.")

    # --- FITUR EXPORT PDF (DI BAWAH TABS) ---
    st.divider()
    
    # Siapkan data untuk dikirim ke PDF Generator
    input_data_pdf = {
        'tarif_listrik': tarif_listrik, 'harga_gas': harga_gas,
        'harga_deterjen': harga_deterjen, 'takaran_det': takaran_det,
        'watt_cuci': watt_cuci, 'durasi_cuci': durasi_cuci, 'durasi_kering': durasi_kering
    }
    hasil_hpp_pdf = {
        'hpp_load': hpp_per_load, 'hpp_kg': hpp_per_kg, 'kapasitas': kapasitas_efektif,
        'biaya_listrik': biaya_listrik, 'biaya_gas': biaya_gas_cycle,
        'biaya_chem': biaya_deterjen_cycle + biaya_parfum_cycle
    }
    hasil_profit_pdf = {
        'target_omzet': target_omzet,
        'laba_bersih': laba_bersih,
        'target_kg': kg_per_hari_needed
    }

    # Kolom untuk tombol download agar rapi di tengah/kanan
    col_d1, col_d2 = st.columns([3, 1])
    with col_d2:
        pdf_bytes = create_pdf(input_data_pdf, hasil_hpp_pdf, hasil_profit_pdf)
        st.download_button(
            label="📄 Download Laporan PDF",
            data=pdf_bytes,
            file_name=f"laporan_laundry_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf",
            use_container_width=True
        )
